# Generated by Django 4.2 on 2023-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMBER', models.IntegerField()),
                ('NAME', models.CharField(max_length=255)),
                ('TYPE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMBER', models.IntegerField()),
                ('NAME', models.CharField(max_length=255)),
                ('TYPE', models.CharField(max_length=255)),
            ],
        ),
    ]
